#Linear SVM for Customer Churn Prediction

**`Problem Statement`**

A telecom company wants to predict whether a customer will churn (leave the service). The company requires a model that is both accurate and interpretable.

In this task, a Linear Support Vector Machine (SVM) classifier is used to predict churn. The model identifies the optimal decision boundary that separates churn and non-churn customers.

The goal is to analyze:

Decision boundary

Support vectors

Effect of regularization parameter (C)

Model generalization performance

Dataset used: Telco Customer Churn Dataset

**`Approach`**

The following steps are followed:

1. Data Loading

The dataset is loaded from the CSV file.

2. Data Preprocessing

Remove missing values

Encode categorical features using one-hot encoding

Convert the target variable (Churn) into numeric form

3. Feature Scaling

SVM is sensitive to feature scale, therefore StandardScaler is applied.

4. Train-Test Split

The dataset is divided using Stratified Train/Test Split to maintain class balance.

5. Model Training

A Linear SVM classifier is trained using different values of C:

C = 0.1

C = 1

C = 10

6. Evaluation Metrics

For each C value the following metrics are calculated:

Confusion Matrix

Accuracy

Precision

Recall

F1 Score

ROC-AUC

Number of Support Vectors

7. Result Comparison

All results are stored in svm_linear_results.csv and predictions are stored in test_predictions.csv.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Load dataset
df = pd.read_csv("Telco-Customer-Churn.csv")

# Fix TotalCharges column
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Drop missing values
df = df.dropna()

# Encode target
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})

# Remove ID column
df = df.drop('customerID', axis=1)

# One-hot encoding
df = pd.get_dummies(df, drop_first=True)

X = df.drop('Churn', axis=1)
y = df['Churn']

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

C_values = [0.1,1,10]

for C in C_values:

    model = LinearSVC(C=C, max_iter=5000)
    model.fit(X_train,y_train)

    preds = model.predict(X_test)

    print("\nC =",C)
    print("Confusion Matrix")
    print(confusion_matrix(y_test,preds))

    print("Accuracy:",accuracy_score(y_test,preds))
    print("Precision:",precision_score(y_test,preds))
    print("Recall:",recall_score(y_test,preds))
    print("F1:",f1_score(y_test,preds))

    print("Support Vectors Approx:",model.coef_.shape)


C = 0.1
Confusion Matrix
[[919 114]
 [167 207]]
Accuracy: 0.8002842928216063
Precision: 0.6448598130841121
Recall: 0.553475935828877
F1: 0.5956834532374101
Support Vectors Approx: (1, 30)

C = 1
Confusion Matrix
[[918 115]
 [164 210]]
Accuracy: 0.8017057569296375
Precision: 0.6461538461538462
Recall: 0.5614973262032086
F1: 0.6008583690987125
Support Vectors Approx: (1, 30)

C = 10
Confusion Matrix
[[918 115]
 [165 209]]
Accuracy: 0.8009950248756219
Precision: 0.6450617283950617
Recall: 0.5588235294117647
F1: 0.5988538681948424
Support Vectors Approx: (1, 30)


**`Interpretation (Effect of C)`**

C = 0.1

Large margin

Allows more misclassification

Lower risk of overfitting

Higher number of support vectors

C = 1

Balanced margin

Better trade-off between bias and variance

Often gives best generalization

C = 10

Small margin

Tries to classify all points correctly

Higher risk of overfitting

**`Conclusion`**

A Linear SVM model was used to predict customer churn.

The analysis showed that:

Support vectors define the decision boundary

Regularization parameter C controls margin width

Small C → wider margin but more errors

Large C → narrower margin but risk of overfitting

Among the tested values, C = 1 provided the best balance between accuracy and generalization, making it the most suitable choice for churn prediction.